# Generated by Django 4.1.6 on 2023-02-08 17:49

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_cliente_fornecedor_rename_nome_produto_nomeprod"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="nomeClie",
            field=models.CharField(max_length=100, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="telefoneClie",
            field=models.CharField(
                max_length=11,
                validators=[core.models.validate_telefone],
                verbose_name="Telefone",
            ),
        ),
    ]
