# Generated by Django 4.1.6 on 2023-02-13 13:47

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_cliente_nomeclie_alter_cliente_telefoneclie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fornecedor",
            name="nomeForn",
            field=models.CharField(max_length=100, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="fornecedor",
            name="telefoneForn",
            field=models.CharField(
                max_length=11,
                validators=[core.models.validate_telefone],
                verbose_name="Telefone",
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="nomeProd",
            field=models.CharField(max_length=100, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="produto",
            name="preco",
            field=models.DecimalField(
                decimal_places=2, max_digits=8, verbose_name="Preço"
            ),
        ),
    ]
