# Generated by Django 4.1.6 on 2023-04-05 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_fornecedor_nomeforn_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fornecedor", options={"verbose_name_plural": "Fornecedores"},
        ),
    ]
